// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef MainWindowUI_h
#define MainWindowUI_h
#include <FL/Fl.H>
#include "MainWindow.h"
#include "LogView.h"
#include "TreeView.h"
#include "TableView.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Output.H>

class MainWindowUI {
public:
  MainWindowUI();
  Fl_Double_Window *mainWindow;
  Fl_Menu_Bar *mainMenuBar;
  static Fl_Menu_Item menu_mainMenuBar[];
private:
  void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
  void cb_Turn_i(Fl_Menu_*, void*);
  static void cb_Turn(Fl_Menu_*, void*);
public:
  TreeView *treeView;
  LogView *logView;
  TableView *tableView;
  ~MainWindowUI();
  void show(int argc, char **argv);
  void init(MainWindow* o);
private:
  MainWindow *mainWndObj; 
};
#endif
