// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "MainWindowUI.h"

void MainWindowUI::cb_Open_i(Fl_Menu_*, void*) {
  mainWndObj->test_cb();
}
void MainWindowUI::cb_Open(Fl_Menu_* o, void* v) {
  ((MainWindowUI*)(o->parent()->user_data()))->cb_Open_i(o,v);
}

Fl_Menu_Item MainWindowUI::menu_mainMenuBar[] = {
 {"&File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Open File...", 0x4006f,  (Fl_Callback*)MainWindowUI::cb_Open, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

MainWindowUI::MainWindowUI() {
  { mainWindow = new Fl_Double_Window(649, 401, "Collection Manager");
    mainWindow->user_data((void*)(this));
    { mainMenuBar = new Fl_Menu_Bar(0, 0, 645, 25);
      mainMenuBar->menu(menu_mainMenuBar);
    } // Fl_Menu_Bar* mainMenuBar
    mainWindow->end();
    mainWindow->resizable(mainWindow);
  } // Fl_Double_Window* mainWindow
}

void MainWindowUI::show(int argc, char **argv) {
  mainWndObj = new MainWindow;
mainWindow->show(argc, argv);
}

MainWindowUI::~MainWindowUI() {
  if(mainWndObj!=NULL)delete mainWndObj;
}
