// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef CollMgrMainUI_h
#define CollMgrMainUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>

class CollMgrMainUI {
public:
  CollMgrMainUI();
  Fl_Double_Window *mainWindow;
  void show(int argc, char **argv);
};
#endif
