// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "CollMgrMainUI.h"

CollMgrMainUI::CollMgrMainUI() {
  { mainWindow = new Fl_Double_Window(887, 515, "Collection Manager");
    mainWindow->user_data((void*)(this));
    mainWindow->end();
    mainWindow->resizable(mainWindow);
  } // Fl_Double_Window* mainWindow
}

void CollMgrMainUI::show(int argc, char **argv) {
  mainWindow->show(argc, argv);
}
