// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "MainWindowUI.h"

void MainWindowUI::cb_Open_i(Fl_Menu_*, void*) {
  mainWndObj->test_cb();
}
void MainWindowUI::cb_Open(Fl_Menu_* o, void* v) {
  ((MainWindowUI*)(o->parent()->user_data()))->cb_Open_i(o,v);
}

void MainWindowUI::cb_Turn_i(Fl_Menu_*, void*) {
  mainWndObj->log_switch_cb();
}
void MainWindowUI::cb_Turn(Fl_Menu_* o, void* v) {
  ((MainWindowUI*)(o->parent()->user_data()))->cb_Turn_i(o,v);
}

Fl_Menu_Item MainWindowUI::menu_mainMenuBar[] = {
 {"&File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Open File...", 0x4006f,  (Fl_Callback*)MainWindowUI::cb_Open, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&View", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Turn on/off Log window", 0,  (Fl_Callback*)MainWindowUI::cb_Turn, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

MainWindowUI::MainWindowUI() {
  { mainWindow = new Fl_Double_Window(646, 400, "Collection Manager");
    mainWindow->user_data((void*)(this));
    { mainMenuBar = new Fl_Menu_Bar(0, 0, 645, 25);
      mainMenuBar->menu(menu_mainMenuBar);
    } // Fl_Menu_Bar* mainMenuBar
    { Fl_Group* o = new Fl_Group(0, 23, 645, 377);
      { treeView = new TreeView(0, 23, 165, 376, "TreeView");
        treeView->box(FL_NO_BOX);
        treeView->color(FL_BACKGROUND2_COLOR);
        treeView->selection_color(FL_BACKGROUND_COLOR);
        treeView->labeltype(FL_NORMAL_LABEL);
        treeView->labelfont(0);
        treeView->labelsize(14);
        treeView->labelcolor(FL_FOREGROUND_COLOR);
        treeView->align(Fl_Align(FL_ALIGN_CENTER));
        treeView->when(FL_WHEN_RELEASE);
        treeView.buildTree();
      } // TreeView* treeView
      { logView = new LogView(405, 239, 240, 158, "LogView");
        logView->box(FL_DOWN_BOX);
        logView->color(FL_BACKGROUND_COLOR);
        logView->selection_color(FL_BACKGROUND_COLOR);
        logView->labeltype(FL_NORMAL_LABEL);
        logView->labelfont(0);
        logView->labelsize(14);
        logView->labelcolor(FL_FOREGROUND_COLOR);
        logView->align(Fl_Align(FL_ALIGN_CENTER));
        logView->when(FL_WHEN_RELEASE);
        LogInit(logView, true);
      } // LogView* logView
      o->end();
      Fl_Group::current()->resizable(o);
    } // Fl_Group* o
    mainWindow->end();
  } // Fl_Double_Window* mainWindow
}

void MainWindowUI::show(int argc, char **argv) {
  mainWndObj = new MainWindow;
mainWndObj->init();
mainWindow->show(argc, argv);

mainWndObj->buildTree(mainTree);
}

MainWindowUI::~MainWindowUI() {
  if(mainWndObj!=NULL)delete mainWndObj;
}
