// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef MainWindowUI_h
#define MainWindowUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "MainWindow.h"
#include <FL/Fl_Menu_Bar.H>

class MainWindowUI {
public:
  MainWindowUI();
  Fl_Double_Window *mainWindow;
  Fl_Menu_Bar *mainMenuBar;
  static Fl_Menu_Item menu_mainMenuBar[];
private:
  void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
public:
  void show(int argc, char **argv);
  ~MainWindowUI();
private:
  MainWindow *mainWndObj; 
};
#endif
