######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 14 10:21:53 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
HEADERS += src/gotocelldialog.h \
           src/iconeditor.h \
           src/mainwindow.h \
           src/sortdialog.h
FORMS += src/gotocelldialog.ui src/mainwindow.ui src/prefs.ui src/sortdialog.ui
SOURCES += src/gotocelldialog.cpp \
           src/iconeditor.cpp \
           src/mainwindow.cpp \
           src/sortdialog.cpp \
           src/TestQt.cpp
RESOURCES += res.qrc
