######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 25 17:11:11 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
SOURCES += src/TestQt.cpp
